version: "3.9"  # optional since v1.27.0
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    networks:
      - backend
    depends_on:
      - wordpress
    volumes:
      - wp-data:/www/wordpress

  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    networks:
      - backend
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp-data:/www/wordpress
    env_file:
      - .env

  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    ports:
      - "5000:5000"
    networks:
      - backend
  redis:
    build: ./requirements/bonus/redis
    image: redis
    networks:
      - backend
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    ports:
      - "21:21"
      - "21000:21000"
    networks:
      - backend
    volumes:
      - wp-data:/home/user
  nodejs:
    build: ./requirements/bonus/nodejs
    image: nodejs
    ports:
      - "9000:9000"
    networks:
      - backend
  backup:
    build: ./requirements/bonus/backup
    image: backup
    volumes:
      - backup-data:/backup
    networks:
      - backend
volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/data/db-data
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/data/wp-data
  backup-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/data/backup
networks:
  backend:
    driver: bridge
