version: "3.9"  # optional since v1.27.0
services:
  nginx:
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    networks:
      - backend
    depends_on:
      - wordpress
    volumes:
      - wp-data:/www/wordpress
    restart: unless-stopped
  mariadb:
    build: ./requirements/mariadb/
    image: mariadb
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env
    restart: unless-stopped
  wordpress:
    build: ./requirements/wordpress/
    image: wordpress
    networks:
      - backend
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp-data:/www/wordpress
    env_file:
      - .env
    restart: unless-stopped
  adminer:
    build: ./requirements/bonus/adminer
    image: adminer
    ports:
      - "5000:5000"
    networks:
      - backend
    restart: unless-stopped
  redis:
    build: ./requirements/bonus/redis
    image: redis
    networks:
      - backend
    restart: unless-stopped
  ftp:
    build: ./requirements/bonus/ftp
    image: ftp
    ports:
      - "21:21"
      - "21000:21000"
    networks:
      - backend
    volumes:
      - wp-data:/home/user
    restart: unless-stopped
  nodejs:
    build: ./requirements/bonus/nodejs
    image: nodejs
    ports:
      - "9000:9000"
    networks:
      - backend
    restart: unless-stopped
  backup:
    build: ./requirements/bonus/backup
    image: backup
    depends_on:
      - wordpress
    volumes:
      - wp-data:/dbdata
      - bp-data:/backup
    restart: unless-stopped
volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/data/db-data
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/data/wp-data
  bp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/data/backup
networks:
  backend:
    driver: bridge
