version: "3.4"  # optional since v1.27.0
services:
  nginx:
    build: ./requirements/nginx/
    ports:
      - "443:443"
    networks:
      - backend
    depends_on:
      - wordpress
    volumes:
      - wp-data:/www/wordpress

  mariadb:
    build: ./requirements/mariadb/
    networks:
      - backend
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress/
    networks:
      - backend
    depends_on:
      - mariadb
      - redis
    volumes:
      - wp-data:/www/wordpress
    env_file:
      - .env

  adminer:
    build: ./requirements/bonus/adminer
    ports:
      - "5000:5000"
    networks:
      - backend
  redis:
    build: ./requirements/bonus/redis
    networks:
      - backend
  ftp:
    build: ./requirements/bonus/ftp
    ports:
      - "21:21"
      - "21000:21000"
    networks:
      - backend
        #volumes:
        #- wp-data:/home

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/Desktop/data/db-data
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/aaqlzim/Desktop/data/wp-data

networks:
  backend:
    driver: bridge
